In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("E:\Coding\APNA CLG [AIML COURSE]\Class Notes given by them\Pandas\spotify-tracks-dataset.csv")

In [3]:
print(df.shape)
print(df.columns.tolist())
print(df.head())
print(df.info())

(114000, 22)
['Unnamed: 0.1', 'Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name', 'popularity', 'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature', 'track_genre']
   Unnamed: 0.1  Unnamed: 0                track_id                 artists  \
0             0           0  5SuOikwiRyPMVoIQDJUgSV             Gen Hoshino
1             1           1  4qPNDBW1i3p13qLCt0Ki3A            Ben Woodward
2             2           2  1iJBSr7s7jYXzM8EGcbK5b  Ingrid Michaelson;ZAYN
3             3           3  6lfxq3CG4xtTiEg7opyCyx            Kina Grannis
4             4           4  5vjLSffimiIP26QG5WcN2K        Chord Overstreet

                                          album_name  \
0                                             Comedy
1                                   Ghost (Acoustic)
2                                     To Begin Again
3  Crazy Rich Asians (Original Motion Picture Sou...
4                                            Hold On

                   track_name  popularity  duration_ms  explicit  \
0                      Comedy          73       230666     False
1            Ghost - Acoustic          55       149610     False
2              To Begin Again          57       210826     False
3  Can't Help Falling In Love          71       201933     False
4                     Hold On          82       198853     False

   danceability  ...  loudness  mode  speechiness  acousticness  \
0         0.676  ...    -6.746     0       0.1430        0.0322
1         0.420  ...   -17.235     1       0.0763        0.9240
2         0.438  ...    -9.734     1       0.0557        0.2100
3         0.266  ...   -18.515     1       0.0363        0.9050
4         0.618  ...    -9.681     1       0.0526        0.4690

   instrumentalness  liveness  valence    tempo  time_signature  track_genre
0          0.000001    0.3580    0.715   87.917               4     acoustic
1          0.000006    0.1010    0.267   77.489               4     acoustic
2          0.000000    0.1170    0.120   76.332               4     acoustic
3          0.000071    0.1320    0.143  181.740               3     acoustic
4          0.000000    0.0829    0.167  119.949               4     acoustic

[5 rows x 22 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0.1      114000 non-null  int64
 1   Unnamed: 0        114000 non-null  int64
 2   track_id          114000 non-null  object
 3   artists           113999 non-null  object
 4   album_name        113999 non-null  object
 5   track_name        113999 non-null  object
 6   popularity        114000 non-null  int64
 7   duration_ms       114000 non-null  int64
 8   explicit          114000 non-null  bool
 9   danceability      114000 non-null  float64
 10  energy            114000 non-null  float64
 11  key               114000 non-null  int64
 12  loudness          114000 non-null  float64
 13  mode              114000 non-null  int64
 14  speechiness       114000 non-null  float64
 15  acousticness      114000 non-null  float64
 16  instrumentalness  114000 non-null  float64
 17  liveness          114000 non-null  float64
 18  valence           114000 non-null  float64
 19  tempo             114000 non-null  float64
 20  time_signature    114000 non-null  int64
 21  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(7), object(5)
memory usage: 18.4+ MB
None

In [4]:
df = df.drop(columns=[ 'Unnamed: 0.1', 'Unnamed: 0'])
df.shape

(114000, 20)

In [5]:
df.shape

(114000, 20)

In [6]:
df.columns.tolist()

['track_id',
 'artists',
 'album_name',
 'track_name',
 'popularity',
 'duration_ms',
 'explicit',
 'danceability',
 'energy',
 'key',
 'loudness',
 'mode',
 'speechiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'valence',
 'tempo',
 'time_signature',
 'track_genre']

In [7]:
df.isnull().sum()

track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [8]:
df[df[['artists' , 'album_name' , 'track_name']].isnull().any(axis=1)]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [9]:
df = df.dropna(subset=['artists' , 'album_name' , 'track_name'])
df.shape

(113999, 20)

In [10]:
df.duplicated().sum()

np.int64(450)

In [11]:
df[df.duplicated(keep = False)].sort_values("track_name").head(10)

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
93397,3KKk48f33mlB56F5L5nbJk,Nikolay Kopylov,Popular Opera Arias,"""Don Carlos"" Roderigo'S Death Aria",0,235547,False,0.167,0.3320,1,-9.888,1,0.0359,0.992,0.191,0.1130,0.0527,62.970,4,romance
93440,3KKk48f33mlB56F5L5nbJk,Nikolay Kopylov,Popular Opera Arias,"""Don Carlos"" Roderigo'S Death Aria",0,235547,False,0.167,0.3320,1,-9.888,1,0.0359,0.992,0.191,0.1130,0.0527,62.970,4,romance
16715,4lvfOnCUxyT3aKKamZ3WXu,Wolfgang Amadeus Mozart;Danielle Laval,Mozart - Inspiring Classics,"12 Variations in C Major on ""Ah, vous dirai-je...",6,41893,False,0.212,0.2210,0,-20.543,1,0.0454,0.980,0.960,0.1490,0.4250,148.759,5,classical
16914,4lvfOnCUxyT3aKKamZ3WXu,Wolfgang Amadeus Mozart;Danielle Laval,Mozart - Inspiring Classics,"12 Variations in C Major on ""Ah, vous dirai-je...",6,41893,False,0.212,0.2210,0,-20.543,1,0.0454,0.980,0.960,0.1490,0.4250,148.759,5,classical
16926,1SZp7sIqzHHh1YMaMu8FL2,Wolfgang Amadeus Mozart;Danielle Laval,Mozart - A Classical Dawn,"12 Variations on an Allegretto in B Flat, K.50...",9,64379,False,0.372,0.0722,10,-24.857,1,0.0331,0.993,0.898,0.0886,0.3240,100.924,4,classical
16726,1SZp7sIqzHHh1YMaMu8FL2,Wolfgang Amadeus Mozart;Danielle Laval,Mozart - A Classical Dawn,"12 Variations on an Allegretto in B Flat, K.50...",9,64379,False,0.372,0.0722,10,-24.857,1,0.0331,0.993,0.898,0.0886,0.3240,100.924,4,classical
16908,5R02WO5PUrHxynXWfheAqN,Wolfgang Amadeus Mozart;Danielle Laval,Mozart: A Night of Classics,"12 Variations on an Allegretto in B Flat, K.50...",24,45532,False,0.637,0.0220,3,-26.353,1,0.0525,0.995,0.909,0.1260,0.1930,89.780,4,classical
16708,5R02WO5PUrHxynXWfheAqN,Wolfgang Amadeus Mozart;Danielle Laval,Mozart: A Night of Classics,"12 Variations on an Allegretto in B Flat, K.50...",24,45532,False,0.637,0.0220,3,-26.353,1,0.0525,0.995,0.909,0.1260,0.1930,89.780,4,classical
16712,0gBtRrMYlHoToeVB3cstKs,Wolfgang Amadeus Mozart;Danielle Laval,Mozart - Inspiring Classics,"12 Variations on an Allegretto in B Flat, K.50...",4,65536,False,0.601,0.0588,10,-27.720,0,0.0747,0.995,0.916,0.0899,0.3540,125.689,4,classical
16911,0gBtRrMYlHoToeVB3cstKs,Wolfgang Amadeus Mozart;Danielle Laval,Mozart - Inspiring Classics,"12 Variations on an Allegretto in B Flat, K.50...",4,65536,False,0.601,0.0588,10,-27.720,0,0.0747,0.995,0.916,0.0899,0.3540,125.689,4,classical

In [12]:
df.drop_duplicates()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [13]:
df.describe()

,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,113999.000000,1.139990e+05,113999.000000,113999.000000,113999.000000,113999.000000,113999.000000,113999.000000,113999.000000,113999.000000,113999.000000,113999.000000,113999.000000,113999.000000
mean,33.238827,2.280312e+05,0.566801,0.641383,5.309126,-8.258950,0.637558,0.084652,0.314907,0.156051,0.213554,0.474066,122.147695,3.904034
std,22.304959,1.072961e+05,0.173543,0.251530,3.559999,5.029357,0.480708,0.105733,0.332522,0.309556,0.190378,0.259261,29.978290,0.432623
min,0.000000,8.586000e+03,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218500,4.000000
50%,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.597500,0.049000,0.273000,0.683000,140.071000,4.000000
max,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [14]:
df["track_genre"].nunique()

114

In [15]:
df["track_genre"].unique()

array(['acoustic', 'afrobeat', 'alt-rock', 'alternative', 'ambient',
       'anime', 'black-metal', 'bluegrass', 'blues', 'brazil',
       'breakbeat', 'british', 'cantopop', 'chicago-house', 'children',
       'chill', 'classical', 'club', 'comedy', 'country', 'dance',
       'dancehall', 'death-metal', 'deep-house', 'detroit-techno',
       'disco', 'disney', 'drum-and-bass', 'dub', 'dubstep', 'edm',
       'electro', 'electronic', 'emo', 'folk', 'forro', 'french', 'funk',
       'garage', 'german', 'gospel', 'goth', 'grindcore', 'groove',
       'grunge', 'guitar', 'happy', 'hard-rock', 'hardcore', 'hardstyle',
       'heavy-metal', 'hip-hop', 'honky-tonk', 'house', 'idm', 'indian',
       'indie-pop', 'indie', 'industrial', 'iranian', 'j-dance', 'j-idol',
       'j-pop', 'j-rock', 'jazz', 'k-pop', 'kids', 'latin', 'latino',
       'malay', 'mandopop', 'metal', 'metalcore', 'minimal-techno', 'mpb',
       'new-age', 'opera', 'pagode', 'party', 'piano', 'pop-film', 'pop',
       'power-pop', 'progressive-house', 'psych-rock', 'punk-rock',
       'punk', 'r-n-b', 'reggae', 'reggaeton', 'rock-n-roll', 'rock',
       'rockabilly', 'romance', 'sad', 'salsa', 'samba', 'sertanejo',
       'show-tunes', 'singer-songwriter', 'ska', 'sleep', 'songwriter',
       'soul', 'spanish', 'study', 'swedish', 'synth-pop', 'tango',
       'techno', 'trance', 'trip-hop', 'turkish', 'world-music'],
      dtype=object)

In [16]:
print(df['explicit'].value_counts())
print(df['mode'].value_counts())
print(df['time_signature'].value_counts())

explicit
False    104252
True       9747
Name: count, dtype: int64
mode
1    72681
0    41318
Name: count, dtype: int64
time_signature
4    101842
3      9195
5      1826
1       973
0       163
Name: count, dtype: int64

In [17]:
genre_popularity = (
    df.groupby('track_genre')['popularity']
    .mean()
    .sort_values(ascending = False)
)
genre_popularity.head(10)

track_genre
pop-film     59.283000
k-pop        56.952953
chill        53.651000
sad          52.379000
grunge       49.594000
indian       49.539000
anime        48.772000
emo          48.128000
sertanejo    47.866000
pop          47.576000
Name: popularity, dtype: float64

In [18]:
genre_counts = df["track_genre"].value_counts()
genre_counts.head(10)

track_genre
acoustic             1000
afrobeat             1000
psych-rock           1000
progressive-house    1000
power-pop            1000
pop                  1000
pop-film             1000
piano                1000
party                1000
pagode               1000
Name: count, dtype: int64

In [19]:
top_genres = genre_popularity.head(10).index

df[df['track_genre'].isin(top_genres)].groupby('track_genre')[
    ['popularity', 'danceability', 'energy', 'valence', 'acousticness']
].mean().sort_values('popularity', ascending=False)

             popularity  danceability    energy   valence  acousticness
track_genre
pop-film      59.283000      0.597146  0.604562  0.529253      0.440696
k-pop         56.952953      0.647879  0.675747  0.556738      0.292571
chill         53.651000      0.664346  0.426723  0.403770      0.534097
sad           52.379000      0.692378  0.462470  0.422050      0.473710
grunge        49.594000      0.457062  0.803290  0.400373      0.053441
indian        49.539000      0.592273  0.567121  0.463024      0.484919
anime         48.772000      0.537451  0.674108  0.434463      0.267734
emo           48.128000      0.599321  0.669967  0.441135      0.195081
sertanejo     47.866000      0.591647  0.710391  0.619325      0.436621
pop           47.576000      0.630441  0.606437  0.506223      0.343693

In [20]:
df[['popularity', 'danceability', 'energy', 'valence',
    'acousticness', 'instrumentalness', 'speechiness',
    'liveness', 'tempo']].corr()['popularity'].sort_values(ascending=False)

popularity          1.000000
danceability        0.035444
tempo               0.013212
energy              0.001053
liveness           -0.005397
acousticness       -0.025458
valence            -0.040522
speechiness        -0.044930
instrumentalness   -0.095147
Name: popularity, dtype: float64

In [22]:
mood_genres = ['happy' , 'sad' , 'chill' , 'sleep' ,'study' , 'party']

In [24]:
df[df['track_genre' ].isin(mood_genres)].shape

(6000, 20)

In [25]:
mood_analysis = ( 
    df[df['track_genre'].isin(mood_genres)]
    .groupby('track_genre')[['energy' , 'valence' , 'danceability' , 'acousticness']]
    .mean()
)

mood_analysis

               energy   valence  danceability  acousticness
track_genre
chill        0.426723  0.403770      0.664346      0.534097
happy        0.910971  0.327467      0.552847      0.057244
party        0.871237  0.681235      0.667191      0.092735
sad          0.462470  0.422050      0.692378      0.473710
sleep        0.342072  0.058188      0.167923      0.657253
study        0.410658  0.402701      0.685240      0.530639

In [26]:
df['duration_min'] = df['duration_ms']/60000
df[['duration_ms' , 'duration_min']].head()

   duration_ms  duration_min
0       230666      3.844433
1       149610      2.493500
2       210826      3.513767
3       201933      3.365550
4       198853      3.314217

In [27]:
df.to_csv('spotify_cleaned.csv' , index = False )

In [29]:
import os
os.path.exists('spotify_cleaned.csv')

True

In [31]:
os.path.abspath('spotify_cleaned.csv')

'C:\\Users\\Amulya\\spotify_cleaned.csv'